apiVersion: v1
kind: PersistentVolume
metadata:
  name: wenxindong-optimum-tpu-volume
spec:
  storageClassName: wenxindong-optimum-tpu-sc
  capacity:
    storage: 1000
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: default
    name: wenxindong-optimum-tpu-claim
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/tpu-vm-gke-testing/regions/us-central2/disks/wenxindong-disk-opt-tpu
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: wenxindong-optimum-tpu-claim
spec:
  storageClassName: wenxindong-optimum-tpu-sc
  volumeName: wenxindong-optimum-tpu-volume
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1000